name=input("Enter name: ")
fname=input("Enter father's name: ")
rollno=input("Enter rollno: ")
dep=input("Enter department: ")
prog=input("Enter undgraduate program: ")
gpa=input("Enter current GPA: ")

print("-----REPORT CARD-----")
print("Name: ",name)
print("Father's name: ",fname)
print("Rollno: ",rollno)
print("Department: ",dep)
print("Undgraduate program: ",prog)
print("GPA: ",gpa)
